// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVDoUn3BXDpN6htwOJiNueqbx_e1v5F7Q',
    appId: '1:65134226710:web:6598f0958230aac5df3437',
    messagingSenderId: '65134226710',
    projectId: 'mini-chat-app-ff65a',
    authDomain: 'mini-chat-app-ff65a.firebaseapp.com',
    storageBucket: 'mini-chat-app-ff65a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGBg2Nvjkty4NtgCa4fFYgN-JBPxmkXQc',
    appId: '1:65134226710:android:270f249dfa5f7116df3437',
    messagingSenderId: '65134226710',
    projectId: 'mini-chat-app-ff65a',
    storageBucket: 'mini-chat-app-ff65a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYZMyDIZm3hgmmgRLB8-WT7rkU4WMy-I',
    appId: '1:65134226710:ios:701b60d086b070c0df3437',
    messagingSenderId: '65134226710',
    projectId: 'mini-chat-app-ff65a',
    storageBucket: 'mini-chat-app-ff65a.appspot.com',
    iosBundleId: 'com.example.miniChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYZMyDIZm3hgmmgRLB8-WT7rkU4WMy-I',
    appId: '1:65134226710:ios:701b60d086b070c0df3437',
    messagingSenderId: '65134226710',
    projectId: 'mini-chat-app-ff65a',
    storageBucket: 'mini-chat-app-ff65a.appspot.com',
    iosBundleId: 'com.example.miniChatApp',
  );
}
